# Generated by Django 5.1.5 on 2025-04-27 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permission_level', models.CharField(choices=[('VIEW_ONLY', 'Voir seulement'), ('CONTROL', 'Contrôler les devices'), ('ADD', 'Ajouter des devices')], default='VIEW_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
