# Generated by Django 5.1.5 on 2025-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guestprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest_permissions',
            field=models.JSONField(blank=True, help_text="Permissions personnalisées pour les invités (ex: { 'can_view': True, 'can_control': False, 'can_add': False })", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('USER', 'User'), ('ADMIN', 'Admin'), ('INVITE', 'Guest')], default='VISITOR', max_length=50),
        ),
        migrations.DeleteModel(
            name='GuestProfile',
        ),
    ]
