# Generated by Django 5.1.5 on 2025-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_display_name_user_guest_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='guest_detail',
        ),
        migrations.AlterField(
            model_name='user',
            name='guest_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('USER', 'User'), ('ADMIN', 'Admin')], default='VISITOR', max_length=50),
        ),
    ]
