# Generated by Django 5.1.5 on 2025-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_display_name_remove_user_guest_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('USER', 'User'), ('ADMIN', 'Admin')], default='VISITOR', max_length=16),
        ),
    ]
