# Generated by Django 5.1.5 on 2025-04-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
        ('users', '000X_update_guest_owner_roles'),
    ]

    operations = [
    ]
