# Generated by Django 5.1.6 on 2025-04-28 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_ROOM', "Création d'une pièce"), ('CREATE_DEVICE', "Création d'un objet"), ('OTHER', 'Autre action')], max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('action_datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique action utilisateur',
                'verbose_name_plural': 'Historiques actions utilisateurs',
                'ordering': ['-action_datetime'],
            },
        ),
    ]
