# Generated by Django 5.1.6 on 2025-04-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250428_1314'),
        ('users', '0008_actionhistory'),
    ]

    operations = [
    ]
