# Generated by Django 5.1.5 on 2025-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0007_merge_20250428_1314_0008_actionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('USER', 'User'), ('ADMIN', 'Admin')], default='VISITOR', max_length=50),
        ),
    ]
