# Generated by Django 5.1.5 on 2025-04-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
    ]
