# Generated by Django 5.2 on 2025-04-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
